// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/PeopleMemoryVideo.tsx": () => import("../components/mockups/PeopleMemoryVideo.tsx"),
  "./components/mockups/ui-designs/AmoledMinimal.tsx": () => import("../components/mockups/ui-designs/AmoledMinimal.tsx"),
  "./components/mockups/ui-designs/Glassmorphism.tsx": () => import("../components/mockups/ui-designs/Glassmorphism.tsx"),
  "./components/mockups/ui-designs/VibrantGradient.tsx": () => import("../components/mockups/ui-designs/VibrantGradient.tsx")
};
